# This is a pattern_builder generated by chatgpt to make patterns in data thats collected by data_collecter.
# "Why is this not in data_collecter" -You. Becase chatgpt needs things broken into steps for it because it struggles to build in 1 step.
# Translation im not spending 5 hours debugging its stupid code.
import mysql.connector
import os
from dotenv import load_dotenv
from tqdm import tqdm
import time

load_dotenv()

# Config
TIMEFRAME = '5m'   # must match raw_candles

# DB
conn = mysql.connector.connect(
    host=os.getenv('DATABASE_HOST'),
    user=os.getenv('DATABASE_USER'),
    password=os.getenv('DATABASE_PASS'),
    database=os.getenv('DATABASE_NAME')
)
cursor = conn.cursor(dictionary=True)

# Get symbols
cursor.execute("SELECT id, symbol FROM symbols")
symbols = cursor.fetchall()
print("SYMBOL ROWS:", symbols)
print("SYMBOL COUNT:", len(symbols))

for sym in symbols:
    symbol_id = sym['id']
    symbol = sym['symbol']

    print(f"\nProcessing {symbol}...")

    cursor.execute("""
        SELECT *
        FROM raw_candles
        WHERE symbol_id = %s AND timeframe = %s
        ORDER BY timestamp ASC
    """, (symbol_id, TIMEFRAME))

    candles = cursor.fetchall()

    print(f"Loaded {len(candles)} candles")

    group_index = 0
    pbar = tqdm(total=len(candles) - 3, desc='Building patterns')

    # Group into 4s
    for i in range(0, len(candles) - 3):

        group = candles[i:i+4]

        if len(group) < 4:
            continue

        start_time = str(group[0]['timestamp'])

        #tqdm.write(f"Checking group: {start_time}")
        cursor.execute("""
            SELECT id FROM pattern_groups
            WHERE symbol_id = %s AND start_time = %s
        """, (symbol_id, start_time))

        exists = cursor.fetchone()
        if exists:
            print("exists:", exists)
            continue

        cursor.execute("""
            INSERT INTO pattern_groups (symbol_id, group_index, start_time)
            VALUES (%s, %s, %s)
        """, (symbol_id, group_index, start_time))

        group_id = cursor.lastrowid

        pbar.update(1)

        candle_difs = []
        total_dif = 0

        for idx, c in enumerate(group):
            dif = float(c['close']) - float(c['open'])
            candle_difs.append(dif)
            total_dif += dif

        cursor.execute("""
            INSERT INTO total_group_differences (group_id, total_value)
            VALUES (%s, %s)
        """, (group_id, round(total_dif, 5)))

        total_dif_id = cursor.lastrowid

        for idx, c in enumerate(group):
            cursor.execute("""
                INSERT INTO candle_differences 
                (total_dif_id, candle_index, difference_value, open_price, high_price, low_price, close_price)
                VALUES (%s,%s,%s,%s,%s,%s,%s)
            """, (
                total_dif_id,
                idx,
                candle_difs[idx],
                c['open'],
                c['high'],
                c['low'],
                c['close']
            ))

        group_index += 1

    conn.commit()
    pbar.close()
    print(f"Finished {symbol}")
    print("candles loaded:", len(candles))
    print("first candle:", candles[0])

print("\nALL DONE")